// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxqktTSHYDhFAsBuqw9PoTXkozMdQoxy8',
    appId: '1:963113311449:android:44aa0030727f7a5c6a32c8',
    messagingSenderId: '963113311449',
    projectId: 'foodies-9d881',
    storageBucket: 'foodies-9d881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_py2odfJ-ZVh1iEpcXzVh8yjWclxctA',
    appId: '1:963113311449:ios:9a30e6f3a502083f6a32c8',
    messagingSenderId: '963113311449',
    projectId: 'foodies-9d881',
    storageBucket: 'foodies-9d881.firebasestorage.app',
    androidClientId: '963113311449-dsrfqm8sa7jjpqe61hoqdedr4d5qh0if.apps.googleusercontent.com',
    iosClientId: '963113311449-0d8e9ggbt91sbj2cepgmgsemm8mnf92f.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodies2FlutterApp',
  );
}
